version: '3.7'
services:
  django:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/django
    command: bash -c 'python manage.py migrate; DJANGO_SUPERUSER_PASSWORD=$ADMIN_PASSWORD python manage.py createsuperuser --noinput --username $ADMIN_USERNAME --email $ADMIN_EMAIL; python manage.py runserver 0.0.0.0:8000'
    ports:
      - 8000:8000
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.develop
      - IS_DOCKER=True
    env_file:
      - ./.env

  aiogram:
    container_name: bot
    build:
      context: telegram_bot
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      - IS_DOCKER=True
    depends_on:
      - django